services:

  hr-service:
    build:
      context: ./services/hr-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - HR_DATABASE_URL=${HR_DATABASE_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
    restart: unless-stopped

  ai-service:
    build:
      context: ./services/ai-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - AI_DATABASE_URL=${AI_DATABASE_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
